# Copyright 2017 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "ts_auto_deps_e2e")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") 

# local_repository(
#     name = "build_bazel_rules_typescript",
#     path = "../../..",
# )

# load("@build_bazel_rules_typescript//:package.bzl", "rules_typescript_dependencies", "rules_typescript_dev_dependencies")

# rules_typescript_dependencies()

# rules_typescript_dev_dependencies()


#http_archive(
#    name = "build_bazel_rules_nodejs",
#    urls = ["https://github.com/bazelbuild/rules_nodejs/archive/0.16.4.zip"],
#    strip_prefix = "rules_nodejs-0.16.4",
#)
local_repository(name = "build_bazel_rules_nodejs", path="../../../../rules_nodejs")
    
load("@build_bazel_rules_nodejs//:package.bzl", "rules_nodejs_dependencies")

rules_nodejs_dependencies()

load("@build_bazel_rules_nodejs//:defs.bzl", "node_repositories", "yarn_install")

node_repositories(preserve_symlinks = True)

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

load("@npm//rules_typescript:package.bzl", "install_rules_typescript")

install_rules_typescript()

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

load("@build_bazel_rules_typescript//:defs.bzl", "ts_setup_workspace")

ts_setup_workspace()
